import 'package:crossword_solver/model/crossword.dart';
import 'package:crossword_solver/model/crossword_node.dart';
import 'package:crossword_solver/model/direction.dart';
import 'package:tuple/tuple.dart';

final nodes = [
  CrosswordNode(
      definition: "model stajenki betlejemskiej",
      positionOfDefinition: const Tuple2<int, int>(0, 0),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(0, 1),
      length: 6),
  CrosswordNode(
      definition: "ten, kto pilnuje, strzeże",
      positionOfDefinition: const Tuple2<int, int>(0, 2),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(1, 2),
      length: 7),
  CrosswordNode(
      definition: "wytrawna wódka zbożowa",
      positionOfDefinition: const Tuple2<int, int>(0, 4),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(0, 3),
      length: 6),
  CrosswordNode(
      definition: "pływacki to kraul",
      positionOfDefinition: const Tuple2<int, int>(0, 6),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(0, 5),
      length: 4),
  CrosswordNode(
      definition: "rygiel",
      positionOfDefinition: const Tuple2<int, int>(0, 7),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(0, 8),
      length: 6),
  CrosswordNode(
      definition: "odmiana sikory",
      positionOfDefinition: const Tuple2<int, int>(0, 7),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(1, 7),
      length: 7),
  CrosswordNode(
      definition: "kontuar",
      positionOfDefinition: const Tuple2<int, int>(0, 9),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(0, 10),
      length: 4),
  CrosswordNode(
      definition: "kontroler biletów",
      positionOfDefinition: const Tuple2<int, int>(0, 9),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(1, 9),
      length: 5),
  CrosswordNode(
      definition: "wywołuje kichanie",
      positionOfDefinition: const Tuple2<int, int>(1, 4),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(1, 5),
      length: 6),
  CrosswordNode(
      definition: "78% powietrza",
      positionOfDefinition: const Tuple2<int, int>(2, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(1, 0),
      length: 4),
  CrosswordNode(
      definition: "tarapaty",
      positionOfDefinition: const Tuple2<int, int>(2, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(2, 1),
      length: 5),
  CrosswordNode(
      definition: "fusy po kawie",
      positionOfDefinition: const Tuple2<int, int>(2, 6),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(2, 7),
      length: 4),
  CrosswordNode(
      definition: "tamuje krew",
      positionOfDefinition: const Tuple2<int, int>(2, 6),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(3, 6),
      length: 4),
  CrosswordNode(
      definition: "szósty dzień tygodnia",
      positionOfDefinition: const Tuple2<int, int>(3, 4),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(4, 4),
      length: 6),
  CrosswordNode(
      definition: "kraina Pyrrusa",
      positionOfDefinition: const Tuple2<int, int>(4, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(3, 0),
      length: 4),
  CrosswordNode(
      definition: "cwibak",
      positionOfDefinition: const Tuple2<int, int>(4, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(4, 1),
      length: 4),
  CrosswordNode(
      definition: "zatoka w atolu",
      positionOfDefinition: const Tuple2<int, int>(4, 5),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(3, 5),
      length: 6),
  CrosswordNode(
      definition: "długi mebel",
      positionOfDefinition: const Tuple2<int, int>(4, 5),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(4, 6),
      length: 4),
  CrosswordNode(
      definition: "od przybytku nie boli",
      positionOfDefinition: const Tuple2<int, int>(4, 10),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(5, 10),
      length: 5),
  CrosswordNode(
      definition: "wpływy z handlu",
      positionOfDefinition: const Tuple2<int, int>(5, 5),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(5, 6),
      length: 5),
  CrosswordNode(
      definition: "składnik czekolady",
      positionOfDefinition: const Tuple2<int, int>(6, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(5, 0),
      length: 5),
  CrosswordNode(
      definition: "rezultat, wynik",
      positionOfDefinition: const Tuple2<int, int>(6, 1),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(7, 1),
      length: 5),
  CrosswordNode(
      definition: "pula w grze",
      positionOfDefinition: const Tuple2<int, int>(6, 3),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(6, 4),
      length: 4),
  CrosswordNode(
      definition: "waga towaru",
      positionOfDefinition: const Tuple2<int, int>(6, 3),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(7, 3),
      length: 5),
  CrosswordNode(
      definition: "atrybut Euterpe",
      positionOfDefinition: const Tuple2<int, int>(6, 8),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(7, 8),
      length: 4),
  CrosswordNode(
      definition: "piaszczysta mielizna",
      positionOfDefinition: const Tuple2<int, int>(6, 9),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(7, 9),
      length: 4),
  CrosswordNode(
      definition: "na wyższe stanowisko",
      positionOfDefinition: const Tuple2<int, int>(7, 5),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(8, 5),
      length: 5),
  CrosswordNode(
      definition: "rodzaj fryzury",
      positionOfDefinition: const Tuple2<int, int>(7, 6),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(7, 7),
      length: 4),
  CrosswordNode(
      definition: "feudum",
      positionOfDefinition: const Tuple2<int, int>(8, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(7, 0),
      length: 5),
  CrosswordNode(
      definition: "w gazie ziemnym",
      positionOfDefinition: const Tuple2<int, int>(8, 2),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(8, 3),
      length: 4),
  CrosswordNode(
      definition: "retro Polak",
      positionOfDefinition: const Tuple2<int, int>(8, 2),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(9, 2),
      length: 7),
  CrosswordNode(
      definition: "król zwierząt",
      positionOfDefinition: const Tuple2<int, int>(8, 7),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(8, 8),
      length: 3),
  CrosswordNode(
      definition: "sentencja",
      positionOfDefinition: const Tuple2<int, int>(8, 7),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(9, 7),
      length: 7),
  CrosswordNode(
      definition: "nad plażą",
      positionOfDefinition: const Tuple2<int, int>(9, 6),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(9, 7),
      length: 4),
  CrosswordNode(
      definition: "tnący owad",
      positionOfDefinition: const Tuple2<int, int>(9, 6),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(10, 6),
      length: 4),
  CrosswordNode(
      definition: "komplet narzędzi",
      positionOfDefinition: const Tuple2<int, int>(10, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(9, 0),
      length: 6),
  CrosswordNode(
      definition: "spec od tortur",
      positionOfDefinition: const Tuple2<int, int>(10, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(10, 1),
      length: 3),
  CrosswordNode(
      definition: "świętuje 05.02",
      positionOfDefinition: const Tuple2<int, int>(10, 4),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(10, 5),
      length: 5),
  CrosswordNode(
      definition: "miano",
      positionOfDefinition: const Tuple2<int, int>(10, 4),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(11, 4),
      length: 5),
  CrosswordNode(
      definition: "narośl na liściu",
      positionOfDefinition: const Tuple2<int, int>(10, 10),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(11, 10),
      length: 5),
  CrosswordNode(
      definition: "grozi w upalny dzień",
      positionOfDefinition: const Tuple2<int, int>(11, 8),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(12, 8),
      length: 4),
  CrosswordNode(
      definition: "przedporcie",
      positionOfDefinition: const Tuple2<int, int>(11, 9),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(12, 9),
      length: 4),
  CrosswordNode(
      definition: "poplecznik",
      positionOfDefinition: const Tuple2<int, int>(12, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(11, 0),
      length: 8),
  CrosswordNode(
      definition: "przy krosnach",
      positionOfDefinition: const Tuple2<int, int>(12, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(13, 0),
      length: 5),
  CrosswordNode(
      definition: "śpiewający ptak",
      positionOfDefinition: const Tuple2<int, int>(12, 1),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(13, 1),
      length: 3),
  CrosswordNode(
      definition: "parktyka sądowa",
      positionOfDefinition: const Tuple2<int, int>(12, 3),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(12, 4),
      length: 7),
  CrosswordNode(
      definition: "2,54 cm",
      positionOfDefinition: const Tuple2<int, int>(12, 3),
      direction: Direction.down,
      solutionStartPosition: const Tuple2<int, int>(13, 3),
      length: 3),
  CrosswordNode(
      definition: "prosty stołek",
      positionOfDefinition: const Tuple2<int, int>(13, 5),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(13, 6),
      length: 5),
  CrosswordNode(
      definition: "drugi pokos łąki",
      positionOfDefinition: const Tuple2<int, int>(14, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(14, 1),
      length: 5),
  CrosswordNode(
      definition: "tłusta gleba z namułów",
      positionOfDefinition: const Tuple2<int, int>(14, 6),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(14, 7),
      length: 4),
  CrosswordNode(
      definition: "kinowa z widzami",
      positionOfDefinition: const Tuple2<int, int>(15, 0),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(15, 1),
      length: 4),
  CrosswordNode(
      definition: "odkryta weranda",
      positionOfDefinition: const Tuple2<int, int>(15, 5),
      direction: Direction.right,
      solutionStartPosition: const Tuple2<int, int>(15, 6),
      length: 5),
];

final Crossword crossword = Crossword(nodes: nodes, row: 16, col: 11);
